### ISSUE TITLE
How to change the voice?

### ISSUE THREAD

**Issue by gersooonn** [rany2/edge-srt-to-speech#16]
I liked your project, I need it for my studies to transform srt into audio, but I can't make it work. Could you give me instructions on how to make it work?

**Comment by rany2** [comment]
What issue are you facing right now?

**Comment by rany2** [comment]
Yes, run `edge-tts --list-voices` and pick a Brazilian Portuguese voice. When you picked a voice use the ShortName as a parameter to edge-srt-to-speech like this:
`edge-srt-to-speech --voice thevoice SRT MP3 `
