### ISSUE TITLE
 skipping a few sentences

### ISSUE THREAD

**Issue by gersooonn** [rany2/edge-srt-to-speech#17]
When I'm watching the clip with the subtitles, I see that some phrases were not spoken, it seems that some words are skipped.
Is there any command that you can put the second voice behind, to be able to speak all the lines of the subtitle?

**Comment by rany2** [comment]
Yes it's possible, just add `edge_tts{voice:YOUR_VOICE}` at the end of the subtitle line where you want to override the voice.

**Comment by gersooonn** [comment]
I added, more is still happening, of not saying a few words, leaving that sound space empty.

**Comment by gersooonn** [comment]
Sabe como posso fazer para corrigir isso? Fica acontecendo em alguns áudios gerado

**Comment by rany2** [comment]
If you do a rerun is it always the same piece that gets ignored?

**Comment by gersooonn** [comment]
Sometimes it happens elsewhere, not in the same place.
But sometimes it happens anyway.
