### ISSUE TITLE
cannot generate audio

### ISSUE THREAD

**Issue by rostok** [rany2/edge-srt-to-speech#7]
There seems to be some kind of problem when generating audio resulting with error:
`TypeError: Communicate.run() got an unexpected keyword argument 'customspeak'`

And it seems that commenting the argument line `customspeak=bool(ssml_template),` in `audio_gen(queue, ssml_template, ssml_variables)` solves it. 

My approach here was quite simple - I just installed edge-srt-to-speech with pip. And run `edge-srt-to-speech --enable-debug --voice pl-PL-MarekNeural  --disable-enhanced-srt W.srt W.mp3`. 

Sorry for this lousy insight I am not proficient with Python.

**Comment by rany2** [comment]
Due to Microsoft closing down the API, custom speak stopped working and so it was removed from edge-tts. I will update it so that features that made use of custom SSML are removed as well.

**Comment by rany2** [comment]
Done https://github.com/rany2/edge-srt-to-speech/commit/8a535ad3cc2abf082147f4b3f10f4b6418a313d7

**Comment by rostok** [comment]
man, that was quick! can confirm it's working now. thanks!
